### ISSUE TITLE
 Different thresholds per status?

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/remote-settings-lambdas#257]
(GitHub doesn't allow transfer of issues across orgs so I manually copy-n-pasted this issue from: https://github.com/mozilla/remote-settings-uptake-health/issues/18)

Currently we only define the error threshold percent globally or per source.

But in some situations we may want to have different thresholds per status.

For example, we could consider that 5% of network errors is acceptable, whereas 2% of signature errors is too high.

**Comment by leplatrem** [comment]
Not applicable anymore
