### ISSUE TITLE
Uptake health will get noisy

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/remote-settings-lambdas#258]
The [`uptake_health` command sends a string to Sentry](https://github.com/mozilla-services/remote-settings-lambdas/blob/3a0dc08e05c0fce40b47a418e1eda1078091e5c0/commands/uptake_health.py#L268). That string contains not just the name but individual numbers. These numbers are about to change every 24h. 

That means, that suppose we get an Sentry notification about the uptake health of `main/foo-bar`. Oh no! We investigate and worry and perhaps even change something in mozilla-central or in some configuration of some server. Either way, those changes will take some time to take effect fully. That means that for every single day thereafter we'll get new Sentry email notifications. Day after day. 

The risk is that the Sentry notification traffic gets too noisy we become desensitized to it and start ignoring them. All of them!

Perhaps it's too early to worry but this issue is for discussing and potentially solving this issue.

**Comment by leplatrem** [comment]
Uptake health [was moved to poucave](https://github.com/mozilla-services/poucave/blob/master/checks/remotesettings/uptake_error_rate.py) ;)
