### ISSUE TITLE
`status` can be missing on new/unused collections

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/remote-settings-lambdas#325]
@autrilla reported this today:

https://irccloud.mozilla.com/pastebin/Uc7rzzBT/

I think some collections have no `status`, or worse yet, `status: null`, and I think we should handle this. At the very least, don't crash. Maybe better would be, for such collections, to check that the data in the corresponding destination collections is `[]`.

**Comment by leplatrem** [comment]
I'm not sure how this happened. Error is now gone when running it locally.

When a «signed» collection is created, it's signed immediately. And then, there should be no way to remove the `status` field.

**Comment by leplatrem** [comment]
See https://github.com/Kinto/kinto-signer/pull/695
