### ISSUE TITLE
Share canonical_json as library

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/remote-settings-lambdas#44]
Especially if the Normandy people are going to use it. They've already discovered some bugs with it (mozilla/normandy#1210, and possibly another one @mythmon ?).

**Comment by mythmon** [comment]
The other issues normandy ran into were mozilla/normandy#381 and a follow up mozilla/normandy#390.

**Comment by leplatrem** [comment]
Related https://github.com/Kinto/kinto-signer/issues/65

**Comment by leplatrem** [comment]
No need for kinto-signer anymore
