### ISSUE TITLE
refresh_signature lambda tries to access a non-existing collection and fails with 403

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/remote-settings-lambdas#49]
On -stage, v4.0.2, the refresh_signature lambda fails with the following error:

```
START RequestId: d05fc3a6-5ed2-11e8-8a09-6373fe64fc8c Version: $LATEST
Looking at /buckets/monitor/collections/changes: 
Looking at /buckets/main-workspace/collections/test-leplatrem: GET /v1/buckets/main-workspace/collections/test-leplatrem - 403 403 - {'code': 403, 'errno': 121, 'error': 'Forbidden', 'message': 'This user cannot access this resource.'}: KintoException
Traceback (most recent call last):
  File "/var/task/aws_lambda.py", line 194, in refresh_signature
    collection_metadata = client.get_collection()['data']
  File "/var/task/kinto_http/__init__.py", line 595, in get_collection
    resp, _ = self.session.request('get', endpoint)
  File "/var/task/kinto_http/session.py", line 123, in request
    raise exception
kinto_http.exceptions.KintoException: GET /v1/buckets/main-workspace/collections/test-leplatrem - 403 403 - {'code': 403, 'errno': 121, 'error': 'Forbidden', 'message': 'This user cannot access this resource.'}

END RequestId: d05fc3a6-5ed2-11e8-8a09-6373fe64fc8c
REPORT RequestId: d05fc3a6-5ed2-11e8-8a09-6373fe64fc8c	Duration: 714.73 ms	Billed Duration: 800 ms 	Memory Size: 128 MB	Max Memory Used: 56 MB	
```

However, the collection in the above error message doesn't exist. The collection exists in `main` and `main-preview` buckets, but not in `main-workspace` bucket.

```
$ curl -s --user "$userpass" https://kinto-writer.stage.mozaws.net/v1/buckets/main-workspace/collections/test-leplatrem | jq .
{
  "code": 404,
  "errno": 110,
  "error": "Not Found",
  "details": {
    "id": "test-leplatrem",
    "resource_name": "collection"
  }
}
```

**Comment by bqbn** [comment]
Upon deleting the said collection from `main` and `main-preview` manually, the refresh_signature lambda is working again.

But still not sure why the lambda tries to access a non-existing collection in the first place, and not sure if this is a bug or expected behavior either.

**Comment by leplatrem** [comment]
I think we have to decide what to do when the source collection is deleted.

a) We could keep the preview and destination ones when the source collections is deleted, and skip collections with 404 status in the lambda. That would mean signature will never be refreshed on those ones (see https://github.com/Kinto/kinto-signer/issues/251)

b) We could delete the preview and destination ones when the source collection is deleted. This won't happen in production anyway.

c) We could give the write permission on the preview and destination collections to the creator of the source collection. This way the user that is allowed to delete the source collection is also allowed to delete the preview and destination manually.

I have a preference for a+c

**Comment by leplatrem** [comment]
We don't do self-service anymore. So deleting is now done via admin commands under control :)
